# Trust Security System - Local Development Web Server
# High Performance PowerShell HTTP Server & Direct Disk CMS Synchronizer

$port = 8080
$prefix = "http://localhost:$port/"
$listener = New-Object System.Net.HttpListener
$listener.Prefixes.Add($prefix)

try {
    $listener.Start()
} catch {
    $port = 8081
    $prefix = "http://localhost:$port/"
    $listener = New-Object System.Net.HttpListener
    $listener.Prefixes.Add($prefix)
    $listener.Start()
}

Write-Host "================================================================" -ForegroundColor Cyan
Write-Host " Trust Security System - Local CMS Server is Running!" -ForegroundColor Green
Write-Host " URL: $prefix" -ForegroundColor Yellow
Write-Host " Admin Panel: ${prefix}admin.html" -ForegroundColor Yellow
Write-Host " Live Website: ${prefix}index.html" -ForegroundColor Yellow
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host " Any changes made in admin.html will be saved DIRECTLY to disk" -ForegroundColor White
Write-Host " and instantly synchronized across ALL browsers & devices!" -ForegroundColor White
Write-Host " Press Ctrl+C in this window to stop the server." -ForegroundColor Gray

$root = $PSScriptRoot
$mimeTypes = @{
    ".html" = "text/html; charset=utf-8"
    ".htm"  = "text/html; charset=utf-8"
    ".css"  = "text/css; charset=utf-8"
    ".js"   = "application/javascript; charset=utf-8"
    ".json" = "application/json; charset=utf-8"
    ".png"  = "image/png"
    ".jpg"  = "image/jpeg"
    ".jpeg" = "image/jpeg"
    ".gif"  = "image/gif"
    ".svg"  = "image/svg+xml"
    ".ico"  = "image/x-icon"
    ".mp4"  = "video/mp4"
    ".webm" = "video/webm"
    ".woff" = "font/woff"
    ".woff2"= "font/woff2"
    ".ttf"  = "font/ttf"
}

# Open browser
Start-Process "$prefix"

while ($listener.IsListening) {
    try {
        $context = $listener.GetContext()
        $request = $context.Request
        $response = $context.Response

        $response.Headers.Add("Access-Control-Allow-Origin", "*")
        $response.Headers.Add("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        $response.Headers.Add("Access-Control-Allow-Headers", "Content-Type")

        if ($request.HttpMethod -eq "OPTIONS") {
            $response.StatusCode = 200
            $response.Close()
            continue
        }

        $urlPath = $request.Url.LocalPath
        if ($urlPath -eq "/") { $urlPath = "/index.html" }

        # API: Save Data
        if ($urlPath -eq "/api/save" -or $urlPath -eq "/api/save.php") {
            if ($request.HttpMethod -eq "POST") {
                $reader = New-Object System.IO.StreamReader($request.InputStream, $request.ContentEncoding)
                $body = $reader.ReadToEnd()
                
                # 1. Save to site-data.json
                $jsonPath = Join-Path $root "data\site-data.json"
                [System.IO.File]::WriteAllText($jsonPath, $body, [System.Text.Encoding]::UTF8)

                # 2. Save to default-content.js
                $jsPath = Join-Path $root "data\default-content.js"
                $jsContent = "/**`n * Trust Security System - Default CMS Baseline Database`n * Auto-generated by Admin CMS Server Engine`n */`nwindow.DEFAULT_SITE_DATA = " + $body + ";`n"
                [System.IO.File]::WriteAllText($jsPath, $jsContent, [System.Text.Encoding]::UTF8)

                $resText = '{"success":true,"message":"Site data saved directly to disk and published to all browsers!"}'
                $buffer = [System.Text.Encoding]::UTF8.GetBytes($resText)
                $response.ContentType = "application/json; charset=utf-8"
                $response.ContentLength64 = $buffer.Length
                $response.OutputStream.Write($buffer, 0, $buffer.Length)
                $response.Close()
                continue
            }
        }

        # API: Get Data
        if ($urlPath -eq "/api/get" -or $urlPath -eq "/api/get.php") {
            $jsonPath = Join-Path $root "data\site-data.json"
            if (Test-Path $jsonPath) {
                $bytes = [System.IO.File]::ReadAllBytes($jsonPath)
                $response.ContentType = "application/json; charset=utf-8"
                $response.ContentLength64 = $bytes.Length
                $response.OutputStream.Write($bytes, 0, $bytes.Length)
            } else {
                $response.StatusCode = 404
            }
            $response.Close()
            continue
        }

        # API: Quotations Inbox
        if ($urlPath -eq "/api/inbox" -or $urlPath -eq "/api/inbox.php") {
            $inboxPath = Join-Path $root "data\inbox.json"
            if ($request.HttpMethod -eq "POST") {
                $reader = New-Object System.IO.StreamReader($request.InputStream, $request.ContentEncoding)
                $body = $reader.ReadToEnd()
                
                $inbox = @()
                if (Test-Path $inboxPath) {
                    try {
                        $raw = [System.IO.File]::ReadAllText($inboxPath)
                        $inbox = ConvertFrom-Json $raw
                    } catch {}
                }
                $newInq = ConvertFrom-Json $body
                $inbox = @($newInq) + $inbox
                $newJson = ConvertTo-Json -InputObject $inbox -Depth 10
                [System.IO.File]::WriteAllText($inboxPath, $newJson, [System.Text.Encoding]::UTF8)

                $resText = '{"success":true,"message":"Inquiry saved successfully!"}'
                $buffer = [System.Text.Encoding]::UTF8.GetBytes($resText)
                $response.ContentType = "application/json"
                $response.ContentLength64 = $buffer.Length
                $response.OutputStream.Write($buffer, 0, $buffer.Length)
                $response.Close()
                continue
            } else {
                if (Test-Path $inboxPath) {
                    $bytes = [System.IO.File]::ReadAllBytes($inboxPath)
                    $response.ContentType = "application/json"
                    $response.ContentLength64 = $bytes.Length
                    $response.OutputStream.Write($bytes, 0, $bytes.Length)
                } else {
                    $buffer = [System.Text.Encoding]::UTF8.GetBytes("[]")
                    $response.ContentType = "application/json"
                    $response.OutputStream.Write($buffer, 0, $buffer.Length)
                }
                $response.Close()
                continue
            }
        }

        # Static File Serving
        $filePath = Join-Path $root ($urlPath.TrimStart('/').Replace('/', '\'))
        if (Test-Path $filePath -PathType Leaf) {
            $ext = [System.IO.Path]::GetExtension($filePath).ToLower()
            $mime = "application/octet-stream"
            if ($mimeTypes.ContainsKey($ext)) { $mime = $mimeTypes[$ext] }
            
            $bytes = [System.IO.File]::ReadAllBytes($filePath)
            $response.ContentType = $mime
            $response.ContentLength64 = $bytes.Length
            $response.OutputStream.Write($bytes, 0, $bytes.Length)
        } else {
            $response.StatusCode = 404
        }
        $response.Close()
    } catch {
        # continue listener loop
    }
}
