<?php
/**
 * Trust Security System - Multi-Backend Universal Save API
 * Saves to MySQL Database + data/site-data.json + data/default-content.js
 * Compatible with cPanel, InfinityFree, Apache, Nginx, PHP 7.x, PHP 8.x
 */

header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'error' => 'Method not allowed. Use POST.']);
    exit;
}

require_once __DIR__ . '/config.php';
require_once __DIR__ . '/db.php';

// 1. Read Input (Handles both raw JSON payload & form-encoded $_POST for InfinityFree compatibility)
$rawInput = file_get_contents('php://input');
$data = null;

if (!empty($rawInput)) {
    $data = json_decode($rawInput, true);
}

if ($data === null && isset($_POST['data'])) {
    $data = json_decode($_POST['data'], true);
} elseif ($data === null && isset($_POST['json'])) {
    $data = json_decode($_POST['json'], true);
}

if ($data === null || !is_array($data)) {
    http_response_code(400);
    echo json_encode(['success' => false, 'error' => 'Invalid or empty JSON data received.']);
    exit;
}

$dbSaved = false;
$jsonSaved = false;
$jsSaved = false;

// 2. Save to MySQL Database (if configured)
try {
    $dbSaved = saveSiteDataToDB($data);
} catch (Exception $e) {
    error_log("Database save failed: " . $e->getMessage());
}

// 3. Save to data/ directory (Flat files)
$dataDir = __DIR__ . '/../data';
if (!is_dir($dataDir)) {
    @mkdir($dataDir, 0777, true);
}

// Save site-data.json
$jsonFile = $dataDir . '/site-data.json';
$jsonStr = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
$jsonSaved = @file_put_contents($jsonFile, $jsonStr) !== false;

// Save default-content.js
$jsFile = $dataDir . '/default-content.js';
$jsContent = "/**\n * Trust Security System - Default CMS Baseline Database\n * Auto-generated by Admin CMS Server Engine\n */\nwindow.DEFAULT_SITE_DATA = " . $jsonStr . ";\n";
$jsSaved = @file_put_contents($jsFile, $jsContent) !== false;

if ($dbSaved || $jsonSaved || $jsSaved) {
    echo json_encode([
        'success' => true,
        'message' => 'Site data successfully saved and published across all browsers and devices!',
        'storage' => [
            'mysql_database' => $dbSaved,
            'json_file' => $jsonSaved,
            'js_file' => $jsSaved
        ]
    ]);
} else {
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'error' => 'Failed writing to both database and file system. Please check folder permissions (chmod 755/777).'
    ]);
}
