<?php
/**
 * Trust Security System - CMS Save API
 * Writes directly to data/site-data.json and data/default-content.js
 * Compatible with all cPanel, Shared Hosting, Apache, Nginx PHP environments
 */

header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'error' => 'Method not allowed']);
    exit;
}

$input = file_get_contents('php://input');
if (empty($input)) {
    http_response_code(400);
    echo json_encode(['success' => false, 'error' => 'No data received']);
    exit;
}

$data = json_decode($input, true);
if ($data === null) {
    http_response_code(400);
    echo json_encode(['success' => false, 'error' => 'Invalid JSON']);
    exit;
}

$dataDir = __DIR__ . '/../data';
if (!is_dir($dataDir)) {
    mkdir($dataDir, 0755, true);
}

// 1. Save to site-data.json
$jsonFile = $dataDir . '/site-data.json';
$jsonSaved = file_put_contents($jsonFile, json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));

// 2. Save to default-content.js
$jsFile = $dataDir . '/default-content.js';
$jsContent = "/**\n * Trust Security System - Default CMS Baseline Database\n * Auto-generated by Admin CMS Server Engine\n */\nwindow.DEFAULT_SITE_DATA = " . json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) . ";\n";
$jsSaved = file_put_contents($jsFile, $jsContent);

if ($jsonSaved !== false && $jsSaved !== false) {
    echo json_encode([
        'success' => true,
        'message' => 'Site data saved successfully and published to all visitors!'
    ]);
} else {
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'error' => 'Failed to write to file system. Please check folder permissions.'
    ]);
}
